# Generated by Django 3.0.5 on 2020-04-28 20:21

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='article_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Duyuruya Dosya Ekleyin'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='İçerik'),
        ),
    ]
