# Generated by Django 3.0.5 on 2020-04-28 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_auto_20200428_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='article_file',
            new_name='announcement_file',
        ),
    ]
