# Generated by Django 3.0.5 on 2020-04-29 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_announcement_youtube'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_date']},
        ),
    ]
