# Generated by Django 3.0.5 on 2020-04-18 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homework', '0003_auto_20200418_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Kitabın İsmi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=50, verbose_name='Yazar'),
        ),
        migrations.AlterField(
            model_name='book',
            name='lesson_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.Lesson', verbose_name='Dersin İsmi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_count',
            field=models.IntegerField(verbose_name='Sayfa Sayısı'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.Book', verbose_name='Kitap'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='content',
            field=models.TextField(verbose_name='İçerik'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulan Zaman'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='final_date',
            field=models.DateField(verbose_name='Bitiş Vakti'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='initial_date',
            field=models.DateField(verbose_name='Başlangıç Vakti'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.Lesson', verbose_name='Ders'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Öğrenci İsmi'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Başlık'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.Topic', verbose_name='Konu'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson_name',
            field=models.CharField(max_length=50, verbose_name='Dersin İsmi'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework.Book', verbose_name='Kitabın İsmi'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(max_length=50, verbose_name='Konu İsmi'),
        ),
    ]
