# Generated by Django 3.0.5 on 2020-04-21 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_auto_20200418_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='false_solved',
            field=models.IntegerField(null=True, verbose_name='Yanlış Çözülen Soru Sayısı'),
        ),
        migrations.AddField(
            model_name='homework',
            name='total_solved',
            field=models.IntegerField(null=True, verbose_name='Toplam Çözülen Soru'),
        ),
        migrations.AddField(
            model_name='homework',
            name='true_solved',
            field=models.IntegerField(null=True, verbose_name='Doğru Çözülen Soru Sayısı'),
        ),
    ]
