# Generated by Django 3.0.5 on 2020-04-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0005_auto_20200421_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='false_solved',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Yanlış Çözülen Soru Sayısı'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='total_solved',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Toplam Çözülen Soru'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='true_solved',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Doğru Çözülen Soru Sayısı'),
        ),
    ]
