# Generated by Django 3.0.5 on 2020-04-29 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0006_auto_20200428_2123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homework',
            options={'ordering': ['-created_date']},
        ),
    ]
